# Generated by Django 3.2.6 on 2022-01-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Product Price')),
                ('photo', models.FileField(blank=True, default='productimage/blank.png', upload_to='productimage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecogroapp.category')),
            ],
        ),
    ]
